# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2998d70ac29db2618f2b6bbaf36d5fe0015f9feadcadd89463bfc85e4847277d0e9756d1b1b388c26eecdfa2bf153ee2eb4ea3c5f1ad862500ebca4751375bf3

test:
  secret_key_base: 674b42d8a01279b5e01cec6709dec6a10d7e4c65534da3c7e1b917b32a21ed9f057c0dd9c0229b5795e8dfcffa7078b4aa93e950f5618e07cd602eda448a7105

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
